// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBNJTjCu-2rp1CQHspSk7O3o2KdO0HvbcU',
    appId: '1:139612602412:web:bd44c8b834e52f72ebd189',
    messagingSenderId: '139612602412',
    projectId: 'campzy-ca5d3',
    authDomain: 'campzy-ca5d3.firebaseapp.com',
    storageBucket: 'campzy-ca5d3.firebasestorage.app',
    measurementId: 'G-N4ZDG36BL6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAX73v4XR6yTssxZDUNmH7cgu6P7To2yTk',
    appId: '1:139612602412:android:90bd22ab9f5e5528ebd189',
    messagingSenderId: '139612602412',
    projectId: 'campzy-ca5d3',
    storageBucket: 'campzy-ca5d3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA3Uf3D1O-bCsYbjoCP1wZRvQA9RbalNBk',
    appId: '1:139612602412:ios:699f11dc25022f00ebd189',
    messagingSenderId: '139612602412',
    projectId: 'campzy-ca5d3',
    storageBucket: 'campzy-ca5d3.firebasestorage.app',
    iosClientId: '139612602412-id1rk97co0mve8qg5l5nr5k865d32nj9.apps.googleusercontent.com',
    iosBundleId: 'com.example.mad',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA3Uf3D1O-bCsYbjoCP1wZRvQA9RbalNBk',
    appId: '1:139612602412:ios:699f11dc25022f00ebd189',
    messagingSenderId: '139612602412',
    projectId: 'campzy-ca5d3',
    storageBucket: 'campzy-ca5d3.firebasestorage.app',
    iosClientId: '139612602412-id1rk97co0mve8qg5l5nr5k865d32nj9.apps.googleusercontent.com',
    iosBundleId: 'com.example.mad',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBNJTjCu-2rp1CQHspSk7O3o2KdO0HvbcU',
    appId: '1:139612602412:web:5ca0f06ffc7f4898ebd189',
    messagingSenderId: '139612602412',
    projectId: 'campzy-ca5d3',
    authDomain: 'campzy-ca5d3.firebaseapp.com',
    storageBucket: 'campzy-ca5d3.firebasestorage.app',
    measurementId: 'G-FR17LDBWN5',
  );
}
